### ISSUE TITLE
通过kingshard分表

### ISSUE THREAD

**Issue by wangzhongyang** [wangzhongyang/books#9]
#### 使用的MySQL Proxy
[kingshard](https://github.com/flike/kingshard)

#### 架构和实现
[kingshard架构设计和功能实现](https://github.com/flike/kingshard/blob/master/doc/KingDoc/architecture_of_kingshard_CN.md)

#### 环境
1. 启动两个MySQL实例：
```bash
# 这里使用MySQL8.0 kingshard 会报错
docker run -it -d --name kingshard-mysql1 -p 3308:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql:5.7
docker run -it -d --name kingshard-mysql2 -p 3309:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql:5.7
```
2. 安装kingshard
我这里通过项目里的dockerfile生成image用docker运行
   1. 生成镜像
    ```bash
    docker build -t kingshard:1.1 .
    ```
    2. 分别在两个MySQL实例上创建库及表，如下：
    ```bash
    # kingshard-mysql1
    +-------------------------+
    | Tables_in_kingshard_db |
    +-------------------------+
    | kingshard_table_0000   |
    | kingshard_table_0001   |
    | kingshard_table_0002   |
    | kingshard_table_0003   |
    +-------------------------+
    # kingshard-mysql2
    +-------------------------+
    | Tables_in_kingshard_db |
    +-------------------------+
    | kingshard_table_0004   |
    | kingshard_table_0005   |
    +-------------------------+
    ```
    表结构：
    ```sql
    CREATE TABLE IF NOT EXISTS kingshard_table_0005 ( id BIGINT(64) UNSIGNED  NOT NULL, str VARCHAR(256), f DOUBLE, e enum('test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7', 'test8', 'test9', 'test10'), u tinyint unsigned, i tinyint, ni tinyint, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    ```
    3. 编写kingshard配置文件
   
    ```yaml
    # kingshard的地址和端口
    addr : 0.0.0.0:9696

    # 连接kingshard的用户名和密码的用户列表
    user_list:
    -
        user :  kingshard
        password : kingshard
    #kingshard的web API 端口
    web_addr : 0.0.0.0:9797
    #调用API的用户名和密码
    web_user : admin
    web_password : admin

    # log级别，[debug|info|warn|error],默认是error
    log_level : debug
    # 打开SQL日志，设置为on;关闭SQL日志，设置为off
    log_sql : on
    #如果设置了该项，则只输出SQL执行时间超过slow_log_time(单位毫秒)的SQL日志，不设置则输出全部SQL日志
    slow_log_time : 100
    #日志文件路径，如果不配置则会输出到终端。
    # log_path : /Users/wangzhongyang/go/src/github.com/flike/kingshard/logs
    # sql黑名单文件路径
    # 所有在该文件中的sql都会被kingshard拒绝转发
    #blacklist_sql_file: /Users/flike/blacklist
    # 只允许下面的IP列表连接kingshard，如果不配置则对连接kingshard的IP不做限制。
    # allow_ips: 127.0.0.1
    # kingshard使用的字符集，如果不设置该选项，则kingshard使用utf8作为默认字符集
    #proxy_charset: utf8mb4

    # 一个node节点表示mysql集群的一个数据分片，包括一主多从（可以不配置从库）
    nodes :
    -
        #node节点名字
        name : kingshard_mysql_node1

        # 连接池中最大空闲连接数，也就是最多与后端DB建立max_conns_limit个连接
        max_conns_limit : 16

        # kingshard连接该node中mysql的用户名和密码，master和slave的用户名和密码必须一致
        user :  root
        password : 123456

        # master的地址和端口
        master : ****:3308

        # slave的地址、端口和读权重，@后面的表示该slave的读权重。可不配置slave
        #slave : 192.168.0.12@2,192.168.0.13@3
        #kingshard在300秒内都连接不上mysql，kingshard则会下线该mysql
        down_after_noalive : 300
    -
        #node节点名字
        name : kingshard_mysql_node2

        # 连接池中最大空闲连接数，也就是最多与后端DB建立max_conns_limit个连接
        max_conns_limit : 16

        # kingshard连接该node中mysql的用户名和密码，master和slave的用户名和密码必须一致
        user :  root
        password : 123456

        # master的地址和端口
        master : ****:3309

        # slave的地址、端口和读权重，@后面的表示该slave的读权重。可不配置slave
        #slave : 192.168.0.12@2,192.168.0.13@3
        #kingshard在300秒内都连接不上mysql，kingshard则会下线该mysql
        down_after_noalive : 300


    # 各用户的分表规则
    schema_list :
    -
        #schema的所属用户名
        user: kingshard
        nodes: [kingshard_mysql_node1,kingshard_mysql_node2]
            #所有未分表的SQL，都会发往默认node。
        default: kingshard_mysql_node1
        shard:
        -
            #分表使用的db
            db : kingshard_db
            #分表名字
            table: kingshard_table
            #分表字段
            key: id
            #分表类型
            type: range
            #分表分布的node
            nodes: [kingshard_mysql_node1, kingshard_mysql_node2]
            #子表个数分布，表示node1有4个子表，
            #node2有2个子表。
            locations: [4,2]
            #表示每个子表包含的最大记录数，也就是说每
            #个子表最多包好10000条记录。即子表1对应的id为[0,10000),子表2[10000,20000)....
            table_row_limit: 10000
    ```

    1. 运行docker
        暴露两个端口，以及挂载配置文件
    ```bash
     docker run -it -d --name kingshard_test \
         -p 9696:9696 \
         -p 9797:9797 \
         -v /.../go/src/github.com/flike/kingshard/ks.yaml:/etc/kingshard/ks.yaml \
         kingshard:1.1
    ```
[*官网安装kingshard （本地运行）* ](https://github.com/flike/kingshard/blob/master/doc/KingDoc/kingshard_install_document.md#%E5%AE%89%E8%A3%85kingshard)

#### 测试
1. 插入数据。
   在这个例子中，总共建了六张表，每张表一万条数据，写表的顺序从0000到0005。  
   *下面插入数据的代码会在插入六万条数据后，错报`Error 1105: shard key not in key range`*
```go

import (
	"fmt"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"testing"
)

func Test_AddRow(t *testing.T) {
	dsn := "kingshard:kingshard@tcp(127.0.0.1:9696)/kingshard_db?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		t.Fatalf("open db failed, error:%s", err.Error())
	}
    
	sql := `insert into kingshard_db.kingshard_table (id, str, f, e, u, i) values `
	sql2 := ""
	for i := 1; i < 65000; i++ {
		sql2 += fmt.Sprintf("(%d, 'abc%d', 3.14, 'test1', 255, -127),\n", i, i)
		if i%1000 == 0 {
			if err = execSql(sql, sql2, db); err != nil {
				t.Fatalf("execSql failed, error:%s", err.Error())
			}
			sql2 = ""
		}
	}
	if err = execSql(sql, sql2, db); err != nil {
		t.Fatalf("execSql 2 failed, error:%s", err.Error())
	}
	fmt.Println("over")
}

func execSql(sql1, sql2 string, db *gorm.DB) error {
	sql2 = sql2[:len(sql2)-2]
	sqlRaw := sql1 + sql2 + ";"
	if err := db.Exec(sqlRaw).Error; err != nil {
		return fmt.Errorf("sql:%s, error:%w", sqlRaw, err)
	}
	return nil
}
```
2. 查询
连接kingshard
```bash
mycli -h 127.0.0.1 -ukingshard -P 9696
```
```sql
select * from kingshard_table where id%10000=1;
```
结果：
```bash
+-------+----------+------+-------+-----+------+--------+
| id    | str      | f    | e     | u   | i    | ni     |
+-------+----------+------+-------+-----+------+--------+
| 40001 | abc40001 | 3.14 | test1 | 255 | -127 | <null> |
| 50001 | abc50001 | 3.14 | test1 | 255 | -127 | <null> |
| 1     | abc1     | 3.14 | test1 | 255 | -127 | <null> |
| 10001 | abc10001 | 3.14 | test1 | 255 | -127 | <null> |
| 20001 | abc20001 | 3.14 | test1 | 255 | -127 | <null> |
| 30001 | abc30001 | 3.14 | test1 | 255 | -127 | <null> |
+-------+----------+------+-------+-----+------+--------+
```
